agent_name: olas_hello_world
author: valory
version: 0.1.0
license: Apache-2.0
description: This is my awesome olas hello world agent.
aea_version: '>=2.0.0, <3.0.0'
fingerprint:
  README.md: bafybeigleiqurgfq6dfdlwhu2z77rtvnkfrge5kaglshj7c4ua6t5i4isy
  __init__.py: bafybeiel7sirsyxhznhhkn5eqsveusrafvobe263zkehyehigk6nan6ovu
fingerprint_ignore_patterns: []
skills: []
connections:
- valory/ledger:0.19.0:bafybeid5uwx4uqxkiibw6kazr7my5mk5kcqg2dx2owtcf7kcpbs2jrns2e
contracts: []
protocols: []
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-cosmos:
    version: ==2.1.0
  open-aea-ledger-ethereum:
    version: ==2.1.0
default_connection: null
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    gnosis:
      address: ${GNOSIS_LEDGER_RPC:str:http://localhost:8545}
      chain_id: ${GNOSIS_CHAIN_ID:int:100}
      poa_chain: ${IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
